import React, { useState } from 'react';
import { Leaf, Droplets, Check, X, ShieldAlert } from 'lucide-react';
import { PRODUCT } from '../data/productData';

export default function IngredientDeepDive() {
  const [activeTab, setActiveTab] = useState('niacinamide');

  const ingredients = [
    {
      id: 'niacinamide',
      name: 'Niacinamide (Vitamin B3)',
      role: 'Cellular Restoration & Tone',
      percentage: 'Optimal Clinical Grade',
      benefits: [
        'Strengthens ceramide synthesis in the lipid barrier',
        'Fades the appearance of hyperpigmentation & post-acne marks',
        'Minimizes visible pores and calms nocturnal inflammation',
        'Shields against trans-epidermal moisture evaporation'
      ],
      science: 'Niacinamide acts as a vital precursor to cellular coenzymes (NAD+/NADH) that power nighttime DNA repair and collagen renewal cycles.'
    },
    {
      id: 'olive-leaf',
      name: 'Olive Leaf Bio-Extract',
      role: 'Antioxidant & Free-Radical Scavenger',
      percentage: 'Wild Mediterranean Source',
      benefits: [
        'Contains 400% higher antioxidant capacity than Vitamin C',
        'Rich in Oleuropein to neutralize daytime oxidative damage',
        'Improves dermal elasticity and prevents premature creping',
        'Soothes redness and restores stressed micro-vascular tone'
      ],
      science: 'Oleuropein polyphenols scavenge lipid peroxides generated by UV and urban smog, allowing dermal cells to focus on nocturnal regeneration.'
    },
    {
      id: 'botanical-lipids',
      name: 'Shea & Botanical Lipids',
      role: 'Nocturnal Moisture Lock',
      percentage: 'Pure Plant Squalane Matrix',
      benefits: [
        'Biomimetic fatty acids that mimic natural skin sebum',
        'Locks active ingredients into the stratum corneum for 8+ hours',
        'Melt-in velvety texture without suffocating pores',
        'Promotes waking with supple, baby-soft bounce'
      ],
      science: 'A lightweight triglyceride lattice prevents moisture evaporation in dry or air-conditioned sleeping environments.'
    }
  ];

  const currentIngredient = ingredients.find(i => i.id === activeTab) || ingredients[0];

  return (
    <section
      id="ingredients"
      className="relative w-full py-20 md:py-32 bg-[#F7F3E8] text-[#27352D] overflow-hidden border-b border-[#DDE2D8]"
    >
      <div className="absolute top-1/2 left-0 w-[500px] h-[500px] bg-[#E8EBDD]/60 rounded-full blur-[110px] pointer-events-none" />
      <div className="grain-overlay" />

      <div className="max-w-7xl mx-auto px-6 md:px-12 relative z-10">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16">
          <div className="inline-flex items-center gap-2 mb-3">
            <span className="w-5 h-[1.5px] bg-[#31483A]" />
            <span className="text-[11px] font-mono tracking-[0.28em] text-[#879B7A] uppercase font-semibold">
              PURE BIO-ACTIVE HARMONY
            </span>
            <span className="w-5 h-[1.5px] bg-[#31483A]" />
          </div>

          <h2 className="font-serif text-3xl sm:text-5xl md:text-6xl font-normal text-[#31483A] tracking-tight leading-[1.08] mb-4">
            The Restorative Formula
          </h2>

          <p className="font-sans text-sm sm:text-base text-[#69736A] font-light max-w-xl mx-auto leading-relaxed">
            Clean botanical extracts unified with pure dermatological science. Zero filler, 100% active integrity.
          </p>
        </div>

        {/* Interactive Tab Selector */}
        <div className="flex flex-wrap items-center justify-center gap-2 sm:gap-3 mb-12">
          {ingredients.map((item) => (
            <button
              key={item.id}
              onClick={() => setActiveTab(item.id)}
              className={`px-5 py-2.5 rounded-full text-xs font-mono tracking-wider uppercase transition-all duration-300 border cursor-pointer ${
                activeTab === item.id
                  ? 'bg-[#31483A] text-white border-[#31483A] font-semibold shadow-md shadow-[#31483A]/15'
                  : 'bg-white/90 text-[#31483A] border-[#C9D2C2] hover:border-[#879B7A] hover:bg-white'
              }`}
            >
              {item.name.split(' (')[0]}
            </button>
          ))}
        </div>

        {/* Active Ingredient Detailed Showcase Card */}
        <div className="p-8 sm:p-12 rounded-3xl mb-16 grid grid-cols-1 lg:grid-cols-12 gap-10 items-center bg-white border border-[#C9D2C2] shadow-[0_4px_24px_rgba(49,72,58,0.04)]">
          
          <div className="lg:col-span-7">
            <div className="inline-block px-3 py-1 rounded-md bg-[#E8EBDD] border border-[#C9D2C2] text-[#31483A] text-[10px] font-mono tracking-widest uppercase mb-3 font-semibold">
              {currentIngredient.percentage}
            </div>

            <h3 className="font-serif text-2xl sm:text-4xl text-[#31483A] font-normal mb-2 tracking-tight">
              {currentIngredient.name}
            </h3>

            <p className="text-xs sm:text-sm font-mono text-[#879B7A] mb-6 font-semibold">
              Primary Role: {currentIngredient.role}
            </p>

            {/* Benefit Checkpoints */}
            <div className="space-y-3 mb-6">
              {currentIngredient.benefits.map((b, idx) => (
                <div key={idx} className="flex items-start gap-3">
                  <div className="w-5 h-5 rounded-full bg-[#E8EBDD] text-[#31483A] flex items-center justify-center shrink-0 mt-0.5">
                    <Check size={12} />
                  </div>
                  <span className="text-xs sm:text-sm text-[#27352D] font-light leading-relaxed">
                    {b}
                  </span>
                </div>
              ))}
            </div>

            {/* Scientific Mechanism */}
            <div className="p-4 rounded-xl bg-[#E8EBDD]/50 border border-[#C9D2C2] text-xs text-[#27352D] font-light leading-relaxed">
              <span className="text-[#31483A] font-mono font-semibold block mb-1">
                CELLULAR MECHANISM:
              </span>
              {currentIngredient.science}
            </div>
          </div>

          {/* Right Column: Existing Light Rounded Visual Container for Traveling Product */}
          <div className="lg:col-span-5 flex items-center justify-center">
            <div
              id="niacinamide-visual-container"
              className="relative w-full max-w-sm aspect-square rounded-2xl overflow-hidden border border-[#C9D2C2] p-6 sm:p-8 flex items-center justify-center bg-gradient-to-b from-[#E8EBDD] to-[#F7F3E8] shadow-sm pointer-events-none"
            >
              <img
                id="niacinamide-fullboxinfo"
                src="/fullboxinfo.png"
                alt="DERMIVA Niacinamide Formulation & Box Architecture"
                className="w-full h-full object-contain filter drop-shadow-[0_12px_28px_rgba(49,72,58,0.12)] select-none"
              />
            </div>
          </div>

        </div>

        {/* Clean Standard Comparison Table */}
        <div className="p-8 sm:p-10 rounded-3xl bg-white border border-[#C9D2C2] shadow-[0_4px_24px_rgba(49,72,58,0.04)]">
          <div className="text-center mb-8">
            <span className="text-[10px] font-mono tracking-widest text-[#879B7A] uppercase block mb-1 font-semibold">
              FORMULATION INTEGRITY
            </span>
            <h4 className="font-serif text-2xl sm:text-3xl text-[#31483A] font-normal">
              Why DERMIVA Stands Apart
            </h4>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
            
            {/* DERMIVA Column */}
            <div className="p-6 rounded-2xl bg-[#E8EBDD]/40 border border-[#879B7A] shadow-sm">
              <div className="flex items-center justify-between pb-4 mb-4 border-b border-[#C9D2C2]">
                <span className="font-serif text-lg text-[#31483A] font-semibold">
                  DERMIVA Repair & Restore
                </span>
                <span className="text-[10px] font-mono text-white bg-[#31483A] px-2.5 py-0.5 rounded-full font-bold">
                  GOLD STANDARD
                </span>
              </div>
              <div className="space-y-3 text-xs text-[#27352D] font-light">
                <div className="flex items-center gap-2.5">
                  <Check size={14} className="text-[#31483A]" />
                  <span>0% Parabens, Sulphates, Silicones, Mineral Oil</span>
                </div>
                <div className="flex items-center gap-2.5">
                  <Check size={14} className="text-[#31483A]" />
                  <span>Bio-active Mediterranean Olive Leaf Polyphenols</span>
                </div>
                <div className="flex items-center gap-2.5">
                  <Check size={14} className="text-[#31483A]" />
                  <span>Clinical Grade Niacinamide (Vitamin B3)</span>
                </div>
                <div className="flex items-center gap-2.5">
                  <Check size={14} className="text-[#31483A]" />
                  <span>Dermatologically tested for sensitive barrier support</span>
                </div>
              </div>
            </div>

            {/* Ordinary Night Creams Column */}
            <div className="p-6 rounded-2xl bg-[#F7F3E8]/70 border border-[#DDE2D8]">
              <div className="flex items-center justify-between pb-4 mb-4 border-b border-[#DDE2D8]">
                <span className="font-serif text-lg text-[#69736A] font-normal">
                  Standard Night Creams
                </span>
                <span className="text-[10px] font-mono text-[#69736A] bg-white border border-[#C9D2C2] px-2 py-0.5 rounded-full font-medium">
                  CONVENTIONAL
                </span>
              </div>
              <div className="space-y-3 text-xs text-[#69736A] font-light">
                <div className="flex items-center gap-2.5">
                  <X size={14} className="text-red-500/80" />
                  <span>Heavy pore-clogging mineral oils & silicones</span>
                </div>
                <div className="flex items-center gap-2.5">
                  <X size={14} className="text-red-500/80" />
                  <span>Synthetic chemical dyes and harsh parabens</span>
                </div>
                <div className="flex items-center gap-2.5">
                  <X size={14} className="text-red-500/80" />
                  <span>Low-grade diluted active concentrations</span>
                </div>
                <div className="flex items-center gap-2.5">
                  <X size={14} className="text-red-500/80" />
                  <span>Greasy residue that stains pillowcases</span>
                </div>
              </div>
            </div>

          </div>
        </div>

      </div>
    </section>
  );
}
